INFO:sagemaker:Creating training-job with name: tf2-object-detection-2025-06-28-20-20-10-053
2025-06-28 20:20:12 Starting - Starting the training job...
2025-06-28 20:20:42 Starting - Preparing the instances for training...
2025-06-28 20:21:13 Downloading - Downloading input data...
2025-06-28 20:21:29 Downloading - Downloading the training image.........
2025-06-28 20:23:00 Training - Training image download completed. Training in progress..2025-06-28 20:23:18,023 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-06-28 20:23:18,058 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-06-28 20:23:18,092 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-06-28 20:23:18,105 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train",
        "val": "/opt/ml/input/data/val"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g5.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": null,
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "model_dir": "/opt/training",
        "num_train_steps": "2000",
        "pipeline_config_path": "pipeline.config",
        "sample_1_of_n_eval_examples": "1"
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        },
        "val": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "instance_groups": [
        "homogeneousCluster"
    ],
    "instance_groups_dict": {
        "homogeneousCluster": {
            "instance_group_name": "homogeneousCluster",
            "instance_type": "ml.g5.xlarge",
            "hosts": [
                "algo-1"
            ]
        }
    },
    "is_hetero": false,
    "is_master": true,
    "is_modelparallel_enabled": null,
    "is_smddpmprun_installed": false,
    "is_smddprun_installed": false,
    "job_name": "tf2-object-detection-2025-06-28-20-20-10-053",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1-418775186567/tf2-object-detection-2025-06-28-20-20-10-053/source/sourcedir.tar.gz",
    "module_name": "run_training.sh",
    "network_interface_name": "eth0",
    "num_cpus": 4,
    "num_gpus": 1,
    "num_neurons": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "current_instance_type": "ml.g5.xlarge",
        "current_group_name": "homogeneousCluster",
        "hosts": [
            "algo-1"
        ],
        "instance_groups": [
            {
                "instance_group_name": "homogeneousCluster",
                "instance_type": "ml.g5.xlarge",
                "hosts": [
                    "algo-1"
                ]
            }
        ],
        "network_interface_name": "eth0",
        "topology": null
    },
    "user_entry_point": "run_training.sh"
}
Environment variables:
SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"model_dir":"/opt/training","num_train_steps":"2000","pipeline_config_path":"pipeline.config","sample_1_of_n_eval_examples":"1"}
SM_USER_ENTRY_POINT=run_training.sh
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.g5.xlarge","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g5.xlarge"}],"network_interface_name":"eth0","topology":null}
SM_INPUT_DATA_CONFIG={"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"val":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["train","val"]
SM_CURRENT_HOST=algo-1
SM_CURRENT_INSTANCE_TYPE=ml.g5.xlarge
SM_CURRENT_INSTANCE_GROUP=homogeneousCluster
SM_CURRENT_INSTANCE_GROUP_HOSTS=["algo-1"]
SM_INSTANCE_GROUPS=["homogeneousCluster"]
SM_INSTANCE_GROUPS_DICT={"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g5.xlarge"}}
SM_DISTRIBUTION_INSTANCE_GROUPS=[]
SM_IS_HETERO=false
SM_MODULE_NAME=run_training.sh
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=4
SM_NUM_GPUS=1
SM_NUM_NEURONS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1-418775186567/tf2-object-detection-2025-06-28-20-20-10-053/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train","val":"/opt/ml/input/data/val"},"current_host":"algo-1","current_instance_group":"homogeneousCluster","current_instance_group_hosts":["algo-1"],"current_instance_type":"ml.g5.xlarge","distribution_hosts":[],"distribution_instance_groups":[],"framework_module":null,"hosts":["algo-1"],"hyperparameters":{"model_dir":"/opt/training","num_train_steps":"2000","pipeline_config_path":"pipeline.config","sample_1_of_n_eval_examples":"1"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"val":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","instance_groups":["homogeneousCluster"],"instance_groups_dict":{"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g5.xlarge"}},"is_hetero":false,"is_master":true,"is_modelparallel_enabled":null,"is_smddpmprun_installed":false,"is_smddprun_installed":false,"job_name":"tf2-object-detection-2025-06-28-20-20-10-053","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1-418775186567/tf2-object-detection-2025-06-28-20-20-10-053/source/sourcedir.tar.gz","module_name":"run_training.sh","network_interface_name":"eth0","num_cpus":4,"num_gpus":1,"num_neurons":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.g5.xlarge","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g5.xlarge"}],"network_interface_name":"eth0","topology":null},"user_entry_point":"run_training.sh"}
SM_USER_ARGS=["--model_dir","/opt/training","--num_train_steps","2000","--pipeline_config_path","pipeline.config","--sample_1_of_n_eval_examples","1"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_CHANNEL_VAL=/opt/ml/input/data/val
SM_HP_MODEL_DIR=/opt/training
SM_HP_NUM_TRAIN_STEPS=2000
SM_HP_PIPELINE_CONFIG_PATH=pipeline.config
SM_HP_SAMPLE_1_OF_N_EVAL_EXAMPLES=1
PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages
Invoking script with the following command:
/bin/sh -c "./run_training.sh --model_dir /opt/training --num_train_steps 2000 --pipeline_config_path pipeline.config --sample_1_of_n_eval_examples 1"
2025-06-28 20:23:18,106 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker Debugger as it is not installed.
===TRAINING THE MODEL==
Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "/usr/local/lib/python3.8/dist-packages/object_detection/eval_util.py", line 35, in <module>
    from object_detection.metrics import coco_evaluation
  File "/usr/local/lib/python3.8/dist-packages/object_detection/metrics/coco_evaluation.py", line 28, in <module>
    from object_detection.utils import object_detection_evaluation
  File "/usr/local/lib/python3.8/dist-packages/object_detection/utils/object_detection_evaluation.py", line 46, in <module>
    from object_detection.utils import label_map_util
  File "/usr/local/lib/python3.8/dist-packages/object_detection/utils/label_map_util.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/protos/string_int_label_map_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 920, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
==EVALUATING THE MODEL==
Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "/usr/local/lib/python3.8/dist-packages/object_detection/eval_util.py", line 35, in <module>
    from object_detection.metrics import coco_evaluation
  File "/usr/local/lib/python3.8/dist-packages/object_detection/metrics/coco_evaluation.py", line 28, in <module>
    from object_detection.utils import object_detection_evaluation
  File "/usr/local/lib/python3.8/dist-packages/object_detection/utils/object_detection_evaluation.py", line 46, in <module>
    from object_detection.utils import label_map_util
  File "/usr/local/lib/python3.8/dist-packages/object_detection/utils/label_map_util.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/protos/string_int_label_map_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 920, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
==EXPORTING THE MODEL==
Traceback (most recent call last):
  File "exporter_main_v2.py", line 104, in <module>
    from object_detection import exporter_lib_v2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/exporter_lib_v2.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.8/dist-packages/object_detection/builders/model_builder.py", line 23, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/usr/local/lib/python3.8/dist-packages/object_detection/builders/anchor_generator_builder.py", line 26, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/protos/anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import flexible_grid_anchor_generator_pb2 as object__detection_dot_protos_dot_flexible__grid__anchor__generator__pb2
  File "/usr/local/lib/python3.8/dist-packages/object_detection/protos/flexible_grid_anchor_generator_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
mv: cannot stat '/tmp/exported/saved_model': No such file or directory
2025-06-28 20:23:28,254 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2025-06-28 20:23:28,254 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
ExitCode 1
ErrorMessage ""
Command "/bin/sh -c ./run_training.sh --model_dir /opt/training --num_train_steps 2000 --pipeline_config_path pipeline.config --sample_1_of_n_eval_examples 1"
2025-06-28 20:23:28,254 sagemaker-training-toolkit ERROR    Encountered exit_code 1

2025-06-28 20:23:44 Uploading - Uploading generated training model
2025-06-28 20:23:44 Failed - Training job failed
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:24                                                                                   │
│                                                                                                  │
│   21 │   base_job_name='tf2-object-detection'                                                    │
│   22 )                                                                                           │
│   23                                                                                             │
│ ❱ 24 estimator.fit(inputs)                                                                       │
│   25                                                                                             │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/telemetry/telemetry │
│ _logging.py:167 in wrapper                                                                       │
│                                                                                                  │
│   164 │   │   │   │   │   caught_ex = e                                                          │
│   165 │   │   │   │   finally:                                                                   │
│   166 │   │   │   │   │   if caught_ex:                                                          │
│ ❱ 167 │   │   │   │   │   │   raise caught_ex                                                    │
│   168 │   │   │   │   │   return response  # pylint: disable=W0150                               │
│   169 │   │   │   else:                                                                          │
│   170 │   │   │   │   logger.debug(                                                              │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/telemetry/telemetry │
│ _logging.py:138 in wrapper                                                                       │
│                                                                                                  │
│   135 │   │   │   │   start_timer = perf_counter()                                               │
│   136 │   │   │   │   try:                                                                       │
│   137 │   │   │   │   │   # Call the original function                                           │
│ ❱ 138 │   │   │   │   │   response = func(*args, **kwargs)                                       │
│   139 │   │   │   │   │   stop_timer = perf_counter()                                            │
│   140 │   │   │   │   │   elapsed = stop_timer - start_timer                                     │
│   141 │   │   │   │   │   extra += f"&x-latency={round(elapsed, 2)}"                             │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/workflow/pipeline_c │
│ ontext.py:346 in wrapper                                                                         │
│                                                                                                  │
│   343 │   │   │                                                                                  │
│   344 │   │   │   return _StepArguments(retrieve_caller_name(self_instance), run_func, *args,    │
│   345 │   │                                                                                      │
│ ❱ 346 │   │   return run_func(*args, **kwargs)                                                   │
│   347 │                                                                                          │
│   348 │   return wrapper                                                                         │
│   349                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/estimator.py:1383   │
│ in fit                                                                                           │
│                                                                                                  │
│   1380 │   │   │   wait = True                                                                   │
│   1381 │   │   │   forward_to_mlflow_tracking_server = True                                      │
│   1382 │   │   if wait:                                                                          │
│ ❱ 1383 │   │   │   self.latest_training_job.wait(logs=logs)                                      │
│   1384 │   │   try:                                                                              │
│   1385 │   │   │   if forward_to_mlflow_tracking_server:                                         │
│   1386 │   │   │   │   from sagemaker.mlflow.forward_sagemaker_metrics import log_sagemaker_job  │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/estimator.py:2768   │
│ in wait                                                                                          │
│                                                                                                  │
│   2765 │   │   │   logs = log_string_map[logs]                                                   │
│   2766 │   │   # If logs are requested, call logs_for_jobs.                                      │
│   2767 │   │   if logs != "None":                                                                │
│ ❱ 2768 │   │   │   self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)  │
│   2769 │   │   else:                                                                             │
│   2770 │   │   │   self.sagemaker_session.wait_for_job(self.job_name)                            │
│   2771                                                                                           │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:6158 in  │
│ logs_for_job                                                                                     │
│                                                                                                  │
│   6155 │   │   │   exceptions.CapacityError: If the training job fails with CapacityError.       │
│   6156 │   │   │   exceptions.UnexpectedStatusException: If waiting and the training job fails.  │
│   6157 │   │   """                                                                               │
│ ❱ 6158 │   │   _logs_for_job(self, job_name, wait, poll, log_type, timeout)                      │
│   6159 │                                                                                         │
│   6160 │   def logs_for_processing_job(self, job_name, wait=False, poll=10):                     │
│   6161 │   │   """Display logs for a given processing job, optionally tailing them until the is  │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:8771 in  │
│ _logs_for_job                                                                                    │
│                                                                                                  │
│   8768 │   │   │   │   last_profiler_rule_statuses = profiler_rule_statuses                      │
│   8769 │                                                                                         │
│   8770 │   if wait:                                                                              │
│ ❱ 8771 │   │   _check_job_status(job_name, description, "TrainingJobStatus")                     │
│   8772 │   │   if dot:                                                                           │
│   8773 │   │   │   print()                                                                       │
│   8774 │   │   # Customers are not billed for hardware provisioning, so billable time is less t  │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:8835 in  │
│ _check_job_status                                                                                │
│                                                                                                  │
│   8832 │   │   │   │   allowed_statuses=["Completed", "Stopped"],                                │
│   8833 │   │   │   │   actual_status=status,                                                     │
│   8834 │   │   │   )                                                                             │
│ ❱ 8835 │   │   raise exceptions.UnexpectedStatusException(                                       │
│   8836 │   │   │   message=message,                                                              │
│   8837 │   │   │   allowed_statuses=["Completed", "Stopped"],                                    │
│   8838 │   │   │   actual_status=status,                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnexpectedStatusException: Error for Training job tf2-object-detection-2025-06-28-20-20-10-053: Failed. Reason: 
AlgorithmError: ExecuteUserScriptError:
ExitCode 1
ErrorMessage ""
Command "/bin/sh -c ./run_training.sh --model_dir /opt/training --num_train_steps 2000 --pipeline_config_path 
pipeline.config --sample_1_of_n_eval_examples 1", exit code: 1. Check troubleshooting guide for common errors: 
https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sdk-troubleshooting.html



pip install protobuf==3.20.3 before running